ad:
  user:
  password:
  server:
  treebase:
aws_endpoint:          http://localhost:9000
# minio user
aws_access_key_id:     FSF3RXUCOHNXRUR2CKYP
aws_secret_access_key: wV40/dVhwUz4kvwumR0JexbBW3ZYB7BmEo2PPSx5
db_host:               postgres
db_port:               5432
db_database:           book_tracker_test
db_username:           postgres
db_password:           postgres
library_nuc_code:      UIU
medusa_admins_group:   Library Medusa Admins
s3_endpoint:           http://localhost:9000
book_bucket:           book-tracker-books-test
book_key_prefix:
temp_bucket:           book-tracker-temp-test
admin_email:           admin@example.org
secret_key_base:       whatever