ad:
  user:
  password:
  server:
  treebase:
db_host:               postgres
db_port:               5432
db_database:           book_tracker
db_username:           postgres
db_password:           postgres
library_nuc_code:      UIU
medusa_admins_group:   Library Medusa Admins
storage:
  books:
    region:            us-east-1
    endpoint:          http://minio:9000
    bucket:            book-tracker-books-test
    key_prefix:
    access_key_id:     FSF3RXUCOHNXRUR2CKYP
    secret_access_key: wV40/dVhwUz4kvwumR0JexbBW3ZYB7BmEo2PPSx5
  temp:
    region:            us-east-1
    endpoint:          http://minio:9000
    bucket:            book-tracker-temp-test
    access_key_id:     FSF3RXUCOHNXRUR2CKYP
    secret_access_key: wV40/dVhwUz4kvwumR0JexbBW3ZYB7BmEo2PPSx5
admin_email:           admin@example.org
secret_key_base:       whatever
