ad:
  user:
  password:
  server:
  treebase:
aws_endpoint:          http://minio:9000
# minio user
aws_access_key_id:     minioadmin
aws_secret_access_key: minioadmin
db_host:               postgres
db_port:               5432
db_database:           book_tracker
db_username:           postgres
db_password:           postgres
library_nuc_code:      UIU
medusa_admins_group:   Library Medusa Admins
s3_endpoint:           http://minio:9000
book_bucket:           book-tracker-books-test
book_key_prefix:
temp_bucket:           book-tracker-temp-test
smtp:
  address:
  port:
  user_name:
  password:
  authentication:       plain
  enable_starttls_auto: true
admin_email:           admin@example.org
secret_key_base:       whatever