# Sample configuration file.
#
# Copy this file to development.yml and test.yml and fill those in.
#
# The production and demo files are encrypted; use
# `rails credentials:edit -e demo/production` to edit them.

# Only needed in demo & production.
hostname:

# Active Directory configuration.
ad:
  user:
  password:
  server:
  treebase:

# Cluster in which ECS tasks are invoked. Only used in demo & production.
ecs_cluster:

# Subnet in which ECS tasks are invoked. Only used in demo & production.
ecs_subnet:

# Security group under which ECS tasks are invoked. Only used in demo &
# production.
ecs_security_group:

# Task definition for ECS tasks. Only used in demo & production.
ecs_async_task_definition:

# Docker container used by ECS tasks. Only used in demo & production.
ecs_async_task_container:

# Database host (PostgreSQL required).
db_host: localhost

# Database port.
db_port: 5432

# Database name.
db_database:

# Database username.
db_username:

# Database password.
db_password:

# UIUC Library's National Union Catalog (NUC) code.
library_nuc_code: UIU

# AD group for Medusa administrators. Only used in demo & production.
medusa_admins_group: Library Medusa Admins

# Configures the S3 storage.
storage:
  books:
    region:            us-east-1
    # Leave blank to use an AWS endpoint.
    endpoint:          http://localhost:9000
    # Name of the S3 bucket containing the MARCXML files.
    bucket:            book-tracker-books
    # Prefix of all MARCXML file keys in the book bucket. For example, if all of
    # the files reside under path/path/path/, that would be the key prefix.
    key_prefix:
    access_key_id:     minioadmin
    secret_access_key: minioadmin
  temp:
    region:            us-east-1
    # Leave blank to use an AWS endpoint.
    endpoint:          http://localhost:9000
    # Name of the S3 bucket to use for temporary files.
    bucket:            book-tracker-temp
    access_key_id:     minioadmin
    secret_access_key: minioadmin

saml:
  sp_entity_id:
  sp_private_key:
  idp_sso_service_url:
  idp_sso_service_binding:

# N.B. 1: this whole hash is assigned as-is to
# `config.action_mailer.smtp_settings`. See:
# https://guides.rubyonrails.org/action_mailer_basics.html#action-mailer-configuration
# N.B. 2: this section is not used or needed in test.yml.
# N.B. 3: if using Gmail in development, and 2FA is enabled, you must set up
# an app password in your Google account, and use that instead of your main
# password.
smtp:
  address:
  port:
  user_name:
  password:
  authentication: plain
  enable_starttls_auto: true

# Addresses to which error mails will be sent.
admin_emails: 

# Generate a value using `rails secret`.
secret_key_base:
