# Sample configuration file.
#
# Copy this file to development.yml and test.yml and fill those in.
#
# The production and demo files are encrypted; use
# `rails credentials:edit -e demo/production` to edit them.

# S3 endpoint URL. Used only in development and test environments.
aws_endpoint:

# Access key ID of an AWS IAM user with permission to access an S3 bucket
# (see `book_bucket`) and invoke ECS tasks. If blank, the `AWS_ACCESS_KEY_ID`
# and `AWS_SECRET_ACCESS_KEY` will be used.
aws_access_key_id:

# Secret access key of the above user.
aws_secret_access_key:

# Cluster in which ECS tasks are invoked. Only used in demo & production.
ecs_cluster:

# Subnet in which ECS tasks are invoked. Only used in demo & production.
ecs_subnet:

# Security group under which ECS tasks are invoked. Only used in demo &
# production.
ecs_security_group:

# Task definition for ECS tasks. Only used in demo & production.
ecs_async_task_definition:

# Docker container used by ECS tasks. Only used in demo & production.
ecs_async_task_container:

# Database host (PostgreSQL required).
db_host: localhost

# Database port.
db_port: 5432

# Database name.
db_database:

# Database username.
db_username:

# Database password.
db_password:

# UIUC Library's National Union Catalog (NUC) code.
library_nuc_code: UIU

# AD group for Medusa administrators. Only used in demo & production.
medusa_admins_group: Library Medusa Admins

# URL of the S3 service hosting the MARCXML files. Leave blank in demo &
# production.
s3_endpoint:

# Name of the S3 bucket containing the MARCXML files.
book_bucket:

# Prefix of all MARCXML file keys in the book bucket. For example, if all of
# the files reside under path/path/path/, that would be the key prefix.
book_key_prefix:

# Name of the S3 bucket to use for temporary files.
temp_bucket:

# N.B. 1: this whole hash is assigned as-is to
# `config.action_mailer.smtp_settings`. See:
# https://guides.rubyonrails.org/action_mailer_basics.html#action-mailer-configuration
# N.B. 2: this section is not used or needed in test.yml.
# N.B. 3: if using Gmail in development, and 2FA is enabled, you must set up
# an app password in your Google account, and use that instead of your main
# password.
smtp:
  address:
  port:
  user_name:
  password:
  authentication: plain
  enable_starttls_auto: true

# Address to which error mails will be sent.
admin_email:

# Generate a value using `rails secret`.
secret_key_base:
