version: '3'

services:
  book-tracker-test:
    build:
      context: .
      dockerfile: docker/book-tracker-test/Dockerfile 
    depends_on:
      - postgres
    command: bash -c "sleep 40 && bin/rails db:prepare & bin/rails test"